### ISSUE TITLE
Matching preferred against supported languages

### ISSUE THREAD

**Issue by xiegeo** [go-macaron/i18n#4]
As brought up by gogits/gogs/issues/2958

Currently, go-macaron/i18n only does a string match for supported languages from the "Accept-Language" http header.
```
// 3. Get language information from 'Accept-Language'.
if len(lang) == 0 {
	al := ctx.Req.Header.Get("Accept-Language")
	if len(al) > 4 {
		al = al[:5] // Only compare first 5 letters.
		if i18n.IsExist(al) {
			lang = al
		}
	}
}
```
 This is a problem when browsers send different language tags for the same language or matching similar languages. The good thing is that golang.org/x/text/language implements this feature.

We should use [language.ParseAcceptLanguage](https://godoc.org/golang.org/x/text/language#ParseAcceptLanguage) to extract the language tags, and [language.Matcher](https://godoc.org/golang.org/x/text/language#Matcher) to select the best language to use. 

An alternative is to add MatchAcceptLanguage(s string) (string, err) to Unknwon/i18n using the above so the calling code will just be:
```
// 3. Get language information from 'Accept-Language'.
if len(lang) == 0 {
	al, err := i18n.MatchAcceptLanguage(ctx.Req.Header.Get("Accept-Language"))
	if err == nil {
		lang = al
	}
}
```

I can do a pull request if you like this idea. The only down side is all the casting between string and language.Tag has a code smell.

**Comment by Unknwon** [comment]
This one should be fixed now, thanks your feedback!
