### ISSUE TITLE
panic: file not found

### ISSUE THREAD

**Issue by ston1th** [go-macaron/i18n#5]
Hi,
I ran into a panic while the `i18n` library tried to open a file that diddn't exist on my filesystem.

Some sort of graceful error handling, replacing the call to panic (https://github.com/go-macaron/i18n/blob/master/i18n.go#L57), would be nice.
If I'm not wrong this would break the API.

**Comment by Unknwon** [comment]
Hi, panic meant for errors too critical to make package work, so I don't think remove panic is a good idea. You shouldn't add those files to the module in the first place if they don't exist.
